spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_URL:localhost:5432/dubs-bot}
    username: ${DATABASE_USERNAME:dubs-bot}
    password: ${DATABASE_PASSWORD:dubs-bot}

  sql:
    init:
      mode: always

discord:
  token: ${DISCORD_TOKEN:}

logging:
  level:
    root: info