spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432/dubs-bot}
    username: ${DATABASE_USERNAME:dubs-bot}
    password: ${DATABASE_PASSWORD:dubs-bot}

  r2dbc:
    url: r2dbc:postgresql://${DATABASE_URL:localhost:5432/dubs-bot}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /

discord:
  token: ${DISCORD_TOKEN:}
  api-key: ${WEB_API_KEY:nope}

server:
  port: ${PORT:8080}