version: 2.1
jobs:
  run-bot-tests:
    docker:
      - image: gradle:7.6.1
    steps:
      - checkout
      - run:
          name: Run JUnit tests
          command: |
            chmod 755 ./gradlew
            ./gradlew test
      - run:
          name: Export JUnit tests
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
      - store_test_results:
          name: JUnit tests
          path: ~/test-results/junit

  build-bot-docker-image:
    docker:
      - image: docker:23.0.5-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker native image with GraalVM
          command: |
            export VERSION=$(cat ./VERSION)
            
            apk add --update openjdk17
            export GRADLE_USER_HOME=`pwd`/.gradle
            
            chmod 755 ./gradlew
            ./gradlew bootBuildImage
            
            echo $GITHUB_ACCESS_TOKEN | docker login ghcr.io -u dubs-bot --password-stdin
            docker push ghcr.io/dubs-bot/dubs-bot:$VERSION

  deploy-bot-docker-image:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run:
          name: Deploy built Docker image to Railway
          command: |
            export VERSION=$(cat ./VERSION)
            
            mkdir -p /tmp/railway
            cd /tmp/railway
            
            echo "FROM ghcr.io/dubs-bot/dubs-bot:$VERSION" > ./Dockerfile
            curl -fsSL https://railway.app/install.sh | sh
            
            railway up --service=bot -d
            
workflows:
  test:
    jobs:
      - run-bot-tests
  build:
    when: << pipeline.parameters.run_build_workflow >>
    jobs:
      - build-bot-docker-image
      - deploy-bot-docker-image:
          requires:
            - build-bot-docker-image

parameters:
  run_build_workflow:
    type: boolean
    default: false