create table users
(
    id          int          not null generated by default as identity primary key,
    user_id     bigint       not null unique,
    user_name   varchar(128)  not null,
    user_avatar varchar(256) not null
);

create table guilds
(
    id         int          not null generated by default as identity primary key,
    guild_id   bigint       not null unique,
    guild_name varchar(128)  not null,
    guild_icon varchar(256) not null
);

create table digit_patterns
(
    id                  int           not null generated by default as identity primary key,
    pattern_key         varchar(32)   not null unique,
    pattern_name        varchar(128)  not null,
    pattern_emoji       varchar(8)    not null,
    pattern_description varchar(2048) not null,
    pattern_points      int           not null check (pattern_points > 0)
);

create table user_scores
(
    id           int    not null generated by default as identity primary key,
    user_id      bigint not null,
    guild_id     bigint not null,
    total_points bigint not null,

    constraint uc_user_scores_user_guild unique (user_id, guild_id)
);

create table user_score_matches
(
    id          int         not null generated by default as identity primary key,
    user_id     bigint      not null,
    guild_id    bigint      not null,
    pattern_key varchar(32) not null,
    count       int         not null,

    constraint fk_pattern_key foreign key (pattern_key) references digit_patterns (pattern_key) on delete cascade
);
